### PR TITLE
Fix for issue #13

### PR DESCRIPTION
**Pull request by wankdanker**
Attached is the fix for the memory leak reported in issue #13. 

Thanks for your help @w1nk!

### CODE REVIEW

**Comment by w1nk** [comment]
Aw man, I tried to beat you to it, now I've hosed up the auto merge :)

**Comment by w1nk** [comment]
Ok, I think I got it merged, yours was way prettier thank mine :P.

**Comment by wankdanker** [comment]
Haha. Awesome. Should we bump the version?

**Comment by w1nk** [comment]
Yeah probably should, that leak sounds like it could be a little nasty under the right circumstances.  I've not even considered versioning, I suppose it's probably time to do that :).

**Pull request merged**
