### PR TITLE
replace `eio_custom` with `uv_queue_work`

### PR DESCRIPTION
**Pull request by wankdanker**
This patch replaces `eio_custom` calls with `uv_queue_work`. This fixes issue #20. 

It is a pretty serious change and I would like it to be tested before it gets out in the wild.

### CODE REVIEW

**Comment by w1nk** [comment]
Assuming libuv works similarly, it looks like you've nailed this, nice!  I did notice one thing we may need to be ready for as we work towards the windows port, we may need to rework the mutex protection around the database queries, I don't believe windows will support pthreads outside of something like cygwin.  It shouldn't be a big deal to ifdef and use the windows locking mechanisms though.

**Comment by wankdanker** [comment]
Good call on the mutex stuff. I asked in #libuv if there was anything that libuv provided which could abstract this from us. I did not get a reply there. It would seem to make sense that if libuv is providing the thread pool, it should provide a way of locking the threads. But my knowledge of working with threads and mutexes is quite limited, so I may be way off base here...

**Comment by wankdanker** [comment]
And we have https://github.com/joyent/libuv/blob/master/include/uv.h#L1448

``` c++
/*
 * The mutex functions return 0 on success, -1 on error
 * (unless the return type is void, of course).
 */
UV_EXTERN int uv_mutex_init(uv_mutex_t* handle);
UV_EXTERN void uv_mutex_destroy(uv_mutex_t* handle);
UV_EXTERN void uv_mutex_lock(uv_mutex_t* handle);
UV_EXTERN int uv_mutex_trylock(uv_mutex_t* handle);
UV_EXTERN void uv_mutex_unlock(uv_mutex_t* handle);
```

**Comment by wankdanker** [comment]
Looks like this is not currently available in the version of uv included with node v0.6.x. And will not be available as the libuv in v0.6 is API-locked according to @TooTallNate. So, we should only push for Windows compatibility for node v0.7 and later to avoid ifdef and having to deal with Windows mutex directly.

**Comment by wankdanker** [comment]
It works! https://github.com/wankdanker/node-odbc/tree/node-v0.7.x

**Comment by w1nk** [comment]
Awesome!  Is there a roadmap for when they expect .7 to stabilize into presumably .8?

**Comment by wankdanker** [comment]
If I recall correctly, I heard isaacs say tentatively June 1st, on http://nodeup.com/sixteen. Feature complete by May 1st.

**Comment by w1nk** [comment]
Using the windows locking API shouldn't be too bad, it's essentially the same as the pthread API with different names, to initialize the mutex:

HANDLE mutex = CreateSemaphore(NULL,1,1,NULL);  // equivalent to pthread_mutex_init

That'll initialize a mutex that can be locked once, that call supports creating semaphores as well but we don't want more than one thread locking it at any given time.  Once initialized:

WaitForSingleObject(mutex, INFINITE);  // wait indefinitely to aquire, equivalent to pthread_mutex_lock
// do stuff
ReleaseSemaphore(mutex, 1, NULL); // equivalent to pthread_mutex_unlock

We'll just need to ifdef based on win32/*nix and alter accordingly until the libuv locking mechanisms become available.  We could probably implement our own mutex's to hide the cross platform guts, but that seems like it'd be overkill since we really only use the mutex to guard the odbc lib.  The win32 odbc implementation may not even suffer the same issue that unixODBC does.

**Comment by wankdanker** [comment]
This will be merged along with a bunch of other stuff when I merge my master branch.

**Pull request closed without merging**
